[package]
name = "bmr-seed"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true
description = "Recover a Minecraft world seed from observed structures and biomes"

[dependencies]
anyhow.workspace = true
bmr-cubiomes.workspace = true
bmr-world.workspace = true
rayon.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
