[package]
name = "bmr-pack"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
flate2.workspace = true
postcard.workspace = true
serde.workspace = true
bmr-fetch.workspace = true
bmr-invert.workspace = true
bmr-prbm.workspace = true
bmr-world.workspace = true
