"""Write fixtures/context/commands.txt: blocks in realistic contexts (stair corners, connected fences / walls /
panes, redstone, doors, double chests, attached blocks, culling, waterlogging, a jumble of every block) that
the debug world, with every state isolated, cannot test. Deterministic (fixed seed).

Usage: py -3 tools/gen_context.py        then: make_world.py context, mirror_fixture.py context
"""
import json
import random

import context_scenes as s
from context_rules import Blocks, finalize
from paths import DEFAULT, FIXTURES

PLOT_STEP = s.SIZE + 2
ORIGINS = [-63 + PLOT_STEP * i for i in range(7)]  # 7x7 plots inside the fixture area -64..63
FULL = {"stone", "stone_bricks", "oak_planks", "cobblestone", "jungle_log", "netherrack", "glass", "sandstone",
        "quartz_block", "deepslate_tiles", "mud_bricks", "polished_blackstone_bricks", "horn_coral_block"}
# invisible, liquid, spreading, or not placeable as a block
NOT_IN_JUMBLE = {"air", "cave_air", "void_air", "water", "lava", "bubble_column", "fire", "soul_fire", "moving_piston",
                 "piston_head", "nether_portal", "end_portal", "end_gateway", "light", "barrier", "structure_void",
                 "frosted_ice"}
GAMERULES = ["gamerule random_tick_speed 0", "gamerule fire_spread_radius_around_player 0",
             "gamerule block_drops false", "gamerule spawn_mobs false"]


def registry() -> dict[str, dict]:
    path = DEFAULT.work / "data" / f"reports-{DEFAULT.mc}" / "reports" / "blocks.json"
    return {k.removeprefix("minecraft:"): v for k, v in json.loads(path.read_text()).items()}


def jumble_pickers(blocks: dict[str, dict]):
    names = sorted(n for n in blocks if n not in NOT_IN_JUMBLE)

    def default_state(rng):
        return rng.choice(names), {}

    def random_state(rng):
        name = rng.choice(names)
        props = {k: rng.choice(v) for k, v in blocks[name].get("properties", {}).items()}
        if "waterlogged" in props:
            props["waterlogged"] = "false"
        return name, props

    return default_state, random_state


def build(rng: random.Random) -> tuple[Blocks, list[str]]:
    blocks = registry()
    defaults = {n: next(s["properties"] for s in b["states"] if s.get("default")) for n, b in blocks.items() if "properties" in b}
    w = Blocks(FULL, defaults)
    default_state, random_state = jumble_pickers(blocks)
    fences = ["oak_fence", "oak_fence", "spruce_fence_gate", "stone"]
    stairs = [("oak", "oak_planks"), ("stone_brick", "stone_bricks"), ("quartz", "quartz_block"),
              ("deepslate_tile", "deepslate_tiles"), ("mud_brick", "mud_bricks"), ("sandstone", "sandstone")]
    connectables = [fences, ["nether_brick_fence", "oak_fence", "stone"], ["cobblestone_wall", "cobblestone_wall", "stone"],
                    ["polished_blackstone_brick_wall", "cobblestone_wall", "oak_fence_gate", "stone"],
                    ["glass_pane", "glass_pane", "stone"], ["magenta_stained_glass_pane", "glass_pane", "glass"],
                    ["iron_bars", "iron_bars", "stone"],
                    ["oak_fence", "cobblestone_wall", "glass_pane", "iron_bars", "oak_fence_gate", "stone"]]
    scenes = [
        *[("stairs", lambda x, z, m=m, f=f: s.stairs(w, rng, x, z, m, f)) for m, f in stairs],
        *[("connectables", lambda x, z, k=k: s.connectables(w, rng, x, z, k)) for k in connectables],
        *[(name, lambda x, z, f=f: f(w, rng, x, z)) for name, f in
          [("redstone", s.redstone), ("redstone", s.redstone), ("slabs", s.slabs), ("doors", s.doors),
           ("containers", s.containers), ("attached", s.attached), ("fire", s.fire), ("culling", s.culling),
           ("pool", s.pool)]],
        *[("jumble", lambda x, z: s.jumble(w, rng, x, z, default_state))] * 4,
        *[("jumble", lambda x, z: s.jumble(w, rng, x, z, random_state))] * 4,
    ]
    plots = [(x, z) for z in ORIGINS for x in ORIGINS]
    assert len(scenes) <= len(plots), f"{len(scenes)} scenes, {len(plots)} plots"
    for (_, scene), (x, z) in zip(scenes, plots):
        scene(x, z)
    finalize(w)
    unknown = {name for name, _ in w.values()} - blocks.keys()
    assert not unknown, f"not in the {DEFAULT.mc} registry: {sorted(unknown)}"
    pools = [p for (name, _), p in zip(scenes, plots) if name == "pool"]
    water = [f"fill {x + 1} {s.Y0} {z + 1} {x + s.SIZE - 2} {s.Y0 + 2} {z + s.SIZE - 2} water replace air" for x, z in pools]
    return w, water


def setblock(p, name, props) -> str:
    state = ",".join(f"{k}={v}" for k, v in props.items())
    return f"setblock {p[0]} {p[1]} {p[2]} minecraft:{name}" + (f"[{state}]" if state else "")


def main() -> None:
    w, water = build(random.Random(1))
    cmds = [setblock(p, *w[p]) for p in sorted(w, key=lambda p: (p[1], p[0], p[2]))]
    out = FIXTURES / "context" / "commands.txt"
    out.write_text("# generated by tools/gen_context.py; do not edit\n" + "\n".join(GAMERULES + cmds + water) + "\n")
    print(f"{len(cmds)} blocks, {len(water)} pools -> {out}")


if __name__ == "__main__":
    main()
